### ISSUE TITLE
Lab: Managing Azure VMs running Windows Server 2019

### ISSUE THREAD

**Issue by garjen55** [MicrosoftLearning/WS-012T00-Windows-Server-2019-Hybrid-and-Azure-IaaS#26]
# Module: 07
#### Step: 08

Description of issue
The last step (everything else worked perfectly). Azure VM Mod07Target should display compliant for W3SVC running in the Azure Policy assignment. I've triggered the scan several times:
![Lab7Issue-f](https://user-images.githubusercontent.com/46939028/114320172-51272500-9ada-11eb-8339-d3068b84de78.jpg)
![Lab7Issue-a](https://user-images.githubusercontent.com/46939028/114320047-c0e8e000-9ad9-11eb-952f-973d21065516.jpg)
The policy is configured:
![Lab7Issue-b](https://user-images.githubusercontent.com/46939028/114320080-e1b13580-9ad9-11eb-9cab-9508c68c59e8.jpg)
I know the web service is running:
![Lab7Issue-c](https://user-images.githubusercontent.com/46939028/114320090-ee358e00-9ad9-11eb-91a1-b36259643cd4.jpg)
I even RDP'd into Mod07Target to verify W3SVC is running
![Lab7Issue-d](https://user-images.githubusercontent.com/46939028/114320121-0f967a00-9ada-11eb-8277-467db7558b84.jpg)
The details for non-compliance not very helpful:
![Lab7Issue-e](https://user-images.githubusercontent.com/46939028/114320149-28069480-9ada-11eb-97e0-824a09d754a4.jpg)

Repro steps:

1. Lab steps
1.
1.

**Comment by TJGitHubUser** [comment]
There was an issue with this lab due to a change that took place last affecting the use of PS remoting and required a change in the lab instructions to disable certificate verification for PS remoting. This should have fixed the issue you were having on lab 7. This same issue affected lab 3. I have not seen this issue reported since. Thanks.
